### ISSUE TITLE
x86 support for simulator?

### ISSUE THREAD

**Issue by tegansnyder** [jammy-huang/TwitterSignIn-iOS#1]
Fresh install from the pod. After importing via:
```swift
//  AppDelegate.swift
import TwitterSignInV1
```
 I get the following error:

> Could not find module 'TwitterSignInV1' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios, at: /var/mobile-ios/Pods/TwitterSignIn/Frameworks/TwitterSignInV1.framework/Modules/TwitterSignInV1.swiftmodule

**Comment by jammy-huang** [comment]
Current version does not support emulator  (x86).
I think this is necessary to support, I will implement it next.

**Comment by jammy-huang** [comment]
Hi, tegan
The new version 1.1.2 already supports simulator, please update pod repo and reimport it.
